// Makes slide show out of a file generated by rst2html
//
// Ole Martin Bjorndalen

slides = [];
current = 0;

function show(num) {
    if(!(num >= 0 && num < slides.length)) {
        return;
    }

    for(i = 0; i < slides.length; i++) {
        slides[i].style.display = 'none'
    }

    slides[num].style.display = 'block';
    current = num;
}

function start() {
    show(0);
}

function next() {
    show(current + 1);
}

function prev() {
    show(current - 1);
}

function on_keydown(event)
{
    switch(event.keyCode) {
    case 33:  // PgUp
    case 38:  // Up
    case 37:  // Left
    case 66:  // b
        prev();
        break;
    case 34:  // PgDn
    case 40:  // Down
    case 39:  // Right
    case 32:  // Space
        next();
        break;
    }
}

function init() {
    slides = document.querySelectorAll(".section");
    document.addEventListener('keydown', on_keydown, false);
    start();
}


window.onload = init;

