// Makes slide show out of a file generated by rst2html
//
// Ole Martin Bjorndalen

slides = [];
current = 0;

function show(num) {
    if(!(num >= 0 && num < slides.length)) {
        return;
    }

    for(i = 0; i < slides.length; i++) {
        slides[i].style.display = 'none'
    }

    slides[num].style.display = 'block';
    current = num;

    var slide_title = slides[num].querySelector('h1').innerHTML;
    document.title = slide_title;
}

function first() {
    show(0);
}

function last() {
    show(slides.length - 1);
}

function next() {
    show(current + 1);
}

function prev() {
    show(current - 1);
}

function on_keydown(event)
{
    var keymap = {
        33: prev, // PgUp
        38: prev, // Up
        37: prev, // Left
        66: prev,  // b
        
        34: next, // PgDn
        40: next, // Down
        39: next, // Right
        32: next, // Space
        
        36: first, // Home
        35: last,  // End
    }
    keymap[event.keyCode]();
}

function on_mousedown(event) {
    if(event.button == 0) {
        next();
    }
}

function on_mousewheel(event) {
    if(event.wheelDeltaY < 0) {
        next();
    } else {
        prev();
    }
}

function is_touch_device() {
  return 'ontouchstart' in window // works on most browsers 
        || 'onmsgesturechange' in window; // works on ie10
};

function init() {
    if(is_touch_device()) {
        // Multitouch devices don't have buttons for paging
        // so let's give them everything on one page.
        return;
    }

    slides = document.querySelectorAll(".section");

    document.addEventListener('keydown', on_keydown, false);
    document.addEventListener('mousedown', on_mousedown, false);
    document.addEventListener('mousewheel', on_mousewheel, false);

    first();
}

window.onload = init;
