// Makes slide show out of a file generated by rst2html
//
// Ole Martin Bjorndalen

slides = [];
current = 0;

function show(num) {
    if(num < 0 || num >= slides.length) {
        return;
    }

    current = num;

    for(i = 0; i < slides.length; i++) {
        if(i == current) {
            slides[num].style.display = 'block';
        } else {
            slides[i].style.display = 'none'
        }
    }

    document.title = slides[num].querySelector('h1').innerHTML;
}

function first() {
    show(0);
}

function last() {
    show(slides.length - 1);
}

function next() {
    show(current + 1);
}

function prev() {
    show(current - 1);
}

function on_keydown(event)
{
    var keymap = {
        33: prev, // PgUp
        38: prev, // Up
        37: prev, // Left
        66: prev, // b
        
        34: next, // PgDn
        40: next, // Down
        39: next, // Right
        32: next, // Space
        
        36: first, // Home
        35: last,  // End
    }
    var func = keymap[event.keyCode];
    if(func) {
        func();
    }
}

function on_mousedown(event) {
    if(event.button == 0) {
        next();
    }
}

function on_mousewheel(event) {
    if(event.wheelDeltaY < 0) {
        next();
    } else {
        prev();
    }
}

function init() {
    slides = document.querySelectorAll(".section");

    document.addEventListener('keydown', on_keydown, false);
    document.addEventListener('mousedown', on_mousedown, false);
    document.addEventListener('mousewheel', on_mousewheel, false);

    first();
}

function is_touch_device() {
  return 'ontouchstart' in window // works on most browsers 
        || 'onmsgesturechange' in window; // works on ie10
};

// Multitouch devices have no buttons so they get everything on one page.
if(!is_touch_device()) {
    window.onload = init;
}
