// Makes slide show out of a file generated by rst2html
//
// This is a part of rstslider.
//
// Author: Ole Martin Bjorndalen (ombdalen@gmail.com)

slides = [];
titles = [];
current = 0;
show_all = false;

function map(func, lst) {
    for(i = 0; i < lst.length; i++) {
        func(lst[i]);
    }    
}

function hide(element) {
    element.style.display = 'none';
}

function show(element) {
    element.style.display = 'block';
}

function goto_slide(num) {
    if(show_all) {
        map(show, slides);
    } else {
        if(num >= 0 && num < slides.length) {
            current = num;
        }
        map(hide, slides);
        show(slides[current]);
    }
}

function first() {
    goto_slide(0);
}

function last() {
    goto_slide(slides.length - 1);
}

function next() {
    goto_slide(current + 1);
}

function prev() {
    goto_slide(current - 1);
}

function toggle_show_all() {
    show_all = !show_all;
    goto_slide(current);
}

function on_keydown(event)
{
    var keymap = {
        33: prev, // PgUp
        38: prev, // Up
        37: prev, // Left
        66: prev, // b
        
        34: next, // PgDn
        40: next, // Down
        39: next, // Right
        32: next, // Space
        
        36: first, // Home
        35: last,  // End

        65: toggle_show_all,  // a
    }
    var func = keymap[event.keyCode];
    if(func) {
        func();
    }
}

function on_mousedown(event) {
    if(event.button == 0) {
        next();
    }
}

function on_mousewheel(event) {
    if(event.wheelDeltaY < 0) {
        next();
    } else {
        prev();
    }
}

function is_touch_device() {
  return 'ontouchstart' in window // works on most browsers 
        || 'onmsgesturechange' in window; // works on ie10
};

function init() {
    slides = document.querySelectorAll(".section");

    document.addEventListener('keydown', on_keydown, false);
    // document.addEventListener('mousedown', on_mousedown, false);
    document.addEventListener('mousewheel', on_mousewheel, false);

    document.title = slides[0].querySelector('h1').innerHTML;

    show_all = is_touch_device();
    first();
}

window.onload = init;
